#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int rotationCount = 360;
task main()
{
	nMotorEncoder[motorC] = 0;

	motor[motorC] = 55;
	while(nMotorEncoder[motorC] <= 2.5*rotationCount)
	{
		//motor[motorC] = 50;
		nxtDisplayCenteredTextLine(4, "Sensor: %f", SensorValue[S2]);
		nxtDisplayCenteredTextLine(5, "Counts: %f", nMotorEncoder[motorC]);
		writeDebugStreamLine("%d", SensorValue[S2]);

		nxtDisplayCenteredTextLine(2, "Rung: %d", floor(nMotorEncoder[motorC]/180));
	}
	motor[motorC] = 0;
	return;
}
