#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int rotationCount = 360;
task main()
{
	nMotorEncoder[motorC] = 0;
	while(nMotorEncoder[motorC] <= 2.5*rotationCount)
	{
		motor[motorC] = 50;
		nxtDisplayCenteredTextLine(4, "Sensor: %f", SensorValue[S2]);
		nxtDisplayCenteredTextLine(5, "Counts: %f", nMotorEncoder[motorC]);

		if(SensorValue[S2] > 42)
		{
			int finalCount = nMotorEncoder[motorC] + 0.19*rotationCount;
			while(nMotorEncoder[motorC] <= finalCount)
			{
				motor[motorC] = 50;
			}
			motor[motorC] = 0;
			return;
		}

	}
	motor[motorC] = 0;
	return;
}
