#pragma config(Motor,  motorB,          arm,           tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************
* Lab 3 : Starter code
* Written by Kaushik Viswanathan,
* Modified by Allan Wang (Jan 2017)

* Feel free to modify any part of these codes.
**********************************************/


/*****************************************
* Main function - Needs changing
*****************************************/
task main()
{

	/* Reset encoders and turn on PID control */
	  nMotorEncoder[arm] = 0;

		float goalTurn = -45;
		// PID for turn control
		float error = goalTurn;
		float last_error = goalTurn;
		float sum_error = 0;
		clearTimer(T1);

		while (1) {
			nxtDisplayCenteredTextLine(1, "Error: %f", error);
			nxtDisplayCenteredTextLine(2, "Turn: %d", nMotorEncoder[arm]);
			int dt = time1[T1];
			if(dt == 0){
				continue;
			}
			clearTimer(T1);

			float actual = nMotorEncoder[arm];
			error = goalTurn - actual;
			float d_error = (error-last_error)/dt;
			sum_error += error;
			last_error = error;
			float kP = 20;
			float kD = 80;
			float kI = .1;
			float feedforward = -100;
			float signal = kP * error + kD * d_error + kI * sum_error + feedforward;


			nxtDisplayCenteredTextLine(3, "Signal: %f", signal);
			nxtDisplayCenteredTextLine(4, "d_error: %f", d_error);
			nxtDisplayCenteredTextLine(5, "sum_error: %f", sum_error);

			motor[arm] = signal;
		}
}
