#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************
* Lab 5 : Path planning
**********************************************/

//Robot's positions
float robot_X = 0, robot_Y = 0, robot_TH = 0.5*PI;

//Wheel diameter and circumference in mm
const float WHEEL_DIAMETER = 55.2;
const float WHEEL_CIRCUMFERENCE = WHEEL_DIAMETER * 3.14159265;
//Distance between wheels in mm
const float WHEEL_DISTANCE = 133.5;
//Number of ticks per mm
const float TICKS_PER_MM = 360/WHEEL_CIRCUMFERENCE;

int velocityUpdateInterval = 1;
int PIDUpdateInterval = 1;

//Waypoints to command

float wp_x[6] = {131.57,583.18,1233.9,999.24,138.68,-3.556}; //(12,12) to (12,36)
float wp_y[6] = {-131.57,-131.57,519.18,753.87,753.87,611.63};

int num_waypoints =6;
float motorPower = 1;
/*****************************************
* Complete this function so that it
* continuously updates the robot's position
*****************************************/
task dead_reckoning()
{
	clearTimer(T1);
	float last_enc_L = nMotorEncoder[motorLeft];
	float last_enc_R = nMotorEncoder[motorRight];

	while(1)
	{
		//
		// Fill in code for numerical integration / position estimation here
		//
		int dt = time1[T1];
		if(dt == 0)
		{
			continue;
		}
		clearTimer(T1);

		int dEncL = nMotorEncoder[motorLeft] - last_enc_L;
		int dEncR = nMotorEncoder[motorRight] - last_enc_R;
		last_enc_L = nMotorEncoder[motorLeft];
		last_enc_R = nMotorEncoder[motorRight];

		//update robot_x and robot_Y and robot angle
		float dispL = dEncL / TICKS_PER_MM;
		float dispR = dEncR / TICKS_PER_MM;
		float disp = (dispL + dispR)/2;
		float angDisp = (dispR - dispL)/WHEEL_DISTANCE;
		robot_TH = robot_TH + angDisp/2;
		robot_X = robot_X + cos(robot_TH)*disp;
		robot_Y = robot_Y + sin(robot_TH)*disp;
		robot_TH = robot_TH + angDisp/2;

		nxtDisplayTextLine(0, "X: %f", robot_X);
		nxtDisplayTextLine(1, "Y: %f", robot_Y);
		nxtDisplayTextLine(2, "t: %f", robot_TH / PI * 180);
		nxtDisplayTextLine(3, "d: %f", sqrt(pow(robot_X - 0, 2) + pow(robot_Y - 0, 2)));

		wait1Msec(velocityUpdateInterval);
	}
}

/**********************************************
* Function that judges if two floats are equal
**********************************************/
bool equal(float a, float b) {
	float epsilon = WHEEL_DIAMETER/2*0.0349/WHEEL_DISTANCE;
	if (abs(a-b) < epsilon) {
		return true;
		} else {
		return false;
	}
}
/*****************************************
* Main function - Needs changing
*****************************************/
task main()
{

	/* Reset encoders and turn on PID control */
	nMotorEncoder[motorRight] = 0;
	nMotorEncoder[motorLeft] = 0;
	nMotorPIDSpeedCtrl[motorRight] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorLeft] = mtrSpeedReg;
	nPidUpdateInterval = PIDUpdateInterval;

	nMaxRegulatedSpeedNxt = 500;
	startTask(dead_reckoning);

	// Start following waypoints
	for(int i = 0; i < num_waypoints; i++)
	{

		float goal_x = wp_x[i];
		float goal_y = wp_y[i];

		// How much to turn with respect to the robot
		float goalTurn = atan2(goal_y-robot_Y, goal_x-robot_X)-robot_TH;
		if (goalTurn > PI)
			goalTurn = goalTurn - 2*PI;
		if (goalTurn < -PI)
			goalTurn = goalTurn + 2*PI;
	  // How much to go with respect to the robot
		float goalStraight = sqrt((goal_x-robot_X)*(goal_x-robot_X) + (goal_y-robot_Y)*(goal_y-robot_Y));
		nxtDisplayCenteredTextLine(4, "GoalTurn: %f", goalTurn/PI*180);
		nxtDisplayCenteredTextLine(5, "GoalStra: %f", goalStraight);

		// PID for turn control
		float error = goalTurn;
		float last_error = goalTurn;
		float sum_error = 0;
		clearTimer(T1);

		while (!equal(error,0)) {

			int dt = time1[T1];
			if(dt == 0){
				continue;
			}
			clearTimer(T1);

			error =atan2(goal_y-robot_Y, goal_x-robot_X)-robot_TH;
 			if (error > PI)
				error = error - 2*PI;
			if (error < -PI)
				error = error + 2*PI;
			float d_error = (error-last_error)/dt;
			sum_error += error;
			last_error = error;
			float kI = 0;
			float kP = 30;
			// Add a little push on the smaller angles
			if (error < PI * 6)
				kP = 40;

			float kD = 1;
			float signal = kP * error + kD * d_error + kI * sum_error;

			motor[motorRight] = signal * motorPower + sgn(error)*10+sgn(error)*.05;
			motor[motorLeft] = signal  *-1* motorPower - sgn(error)*10;

		}
		motor[motorRight] = 0;
		motor[motorLeft] = 0;

		wait1Msec(250);

		float start_X = robot_X;
		float start_Y = robot_Y;

		// PID for straight control
		error = goalStraight;
		last_error = goalStraight;
		sum_error = 0;
		clearTimer(T1);
		clearTimer(T2);

		while(error>7){

			int dt = time1[T1];

			if(dt == 0){
				continue;
			}
			clearTimer(T1);

			// DIstance away from last waypoint
			float actual =  sqrt(pow(robot_X - start_X, 2) + pow(robot_Y - start_Y, 2));
			// Distance away to the next waypoint
			float supposed =  sqrt(pow(goal_x - start_X, 2) + pow(goal_y - start_Y, 2));
			error = supposed-actual;
			nxtDisplayCenteredTextLine(6, "SError: %f", error);
			float d_error = (error-last_error)/dt;
			sum_error += error;
			last_error = error;

			float kI = 0;
			float kP = 0.02;
			float kD = 50;

			float signal = kP * error + kD * d_error + kI * sum_error;
			// Limit the max signal
			if (signal > 50)
				signal = 50;


			nxtDisplayCenteredTextLine(5, "Signal: %f", signal);

			// Within the ramp time the robot gradually speed up to max speed
			int ramp_dt = time1[T2];
			float ramp_time = 2000.0;
			int feedforward = 70;
			int input = signal * motorPower + sgn(error) * feedforward;
			if (ramp_dt < ramp_time){
				input = input * (1- (ramp_time - ramp_dt)/ramp_time);
				nxtDisplayCenteredTextLine(7, "ramp_dt: %d", input);
			}

			motor[motorRight] = input+1.5;
			motor[motorLeft] = input;
		}

		motor[motorRight] = 0;
		motor[motorLeft] = 0;
		wait1Msec(400);
	}
}
