#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          motorRight,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorLeft,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**********************************************
* Lab 3 : Starter code
* Written by Kaushik Viswanathan,
* Modified by Allan Wang (Jan 2017)

* Feel free to modify any part of these codes.
**********************************************/
//Set parameters
const int THRESHOLD = 40;
const int MOTOR_POWER = 30;	 //Base motor power to control the speed
const int UPDATE_INTERVAL = 1; //Delay updates by x miliseconds

/*****************************************
* Main function - Needs changing
*****************************************/


task main()
{
	//Wait for sensor initialization
	wait1Msec(50);

	clearTimer(T1);

	float feedforward = .5*MOTOR_POWER;
	float additional_ff = .5*MOTOR_POWER;
	// Find the line by turning left, then if line is not found within angle, turn right
	while(SensorValue[S2] >= THRESHOLD ){
		nxtDisplayTextLine(0, "Searching");
			motor[motorLeft] = -1*MOTOR_POWER;
			motor[motorRight] = MOTOR_POWER;
	}

	// Start line following
	while(1){
		nxtDisplayTextLine(0, "Following");
		if(SensorValue[S2] < THRESHOLD){ // Seeing the black line
			nxtDisplayTextLine(1, "Black");
			motor[motorRight] = MOTOR_POWER;
			motor[motorLeft] = MOTOR_POWER +feedforward; //Left Motor
			nxtDisplayTextLine(2, "MotorR: %f", motor[motorRight]);
				nxtDisplayTextLine(3, "MotorL: %f", motor[motorLeft]);
				nxtDisplayTextLine(4, "Light: %d", SensorValue[S2]);

		}
		else{
			nxtDisplayTextLine(1, "White");
			motor[motorRight] = MOTOR_POWER -additional_ff/2;
			motor[motorLeft] = MOTOR_POWER +feedforward+additional_ff/2; //Left Motor
			nxtDisplayTextLine(2, "MotorR: %f", motor[motorRight]);
				nxtDisplayTextLine(3, "MotorL: %f", motor[motorLeft]);
					nxtDisplayTextLine(4, "Light: %d", SensorValue[S2]);
		}
		wait1Msec(UPDATE_INTERVAL);
	}
}
